CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ACCOUNT_TYPE VARCHAR2(20),
    BRANCH_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE BRANCH (
    BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR2(100),
    CITY VARCHAR2(50)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR2(100),
    DOB DATE,
    KYC_STATUS VARCHAR2(20)
);

CREATE TABLE REGULATORY_FLAGS (
    CUSTOMER_ID INT,
    FLAG_CODE VARCHAR2(20),
    FLAG_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TRANSACTION (
    TRANSACTION_ID INT PRIMARY KEY,
    ACCOUNT_ID INT,
    AMOUNT NUMBER,
    TRANSACTION_TYPE VARCHAR2(20),
    TRANSACTION_DATE DATE,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);