CREATE TABLE IF NOT EXISTS AML_CUSTOMER_TRANSACTIONS (
    CUSTOMER_ID INT,
    NAME STRING,
    ACCOUNT_ID INT,
    TRANSACTION_ID INT,
    AMOUNT DOUBLE,
    TRANSACTION_TYPE STRING,
    TRANSACTION_DATE DATE
) USING DELTA;

CREATE TABLE IF NOT EXISTS BRANCH_SUMMARY_REPORT (
    BRANCH_ID INT,
    BRANCH_NAME STRING,
    TOTAL_TRANSACTIONS BIGINT,
    TOTAL_AMOUNT DOUBLE
) USING DELTA;