spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Talon.One integration properties
# Replace with your actual Talon.One API key and URL
# Example: https://YOUR_DOMAIN.talon.one

talonone:
  api:
    key: YOUR_TALONONE_API_KEY
    url: https://YOUR_TALONONE_DOMAIN.talon.one

server:
  port: 8080
